<?php
/**
 * Address
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Address Class Doc Comment
 *
 * @category Class
 * @description Indirizzo del Soggetto
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Address implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Address';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'descrizione' => 'string',
        'cap' => 'string',
        'codice_comune' => 'string',
        'descrizione_comune' => 'string',
        'codice_comune_istat' => 'string',
        'provincia' => 'string',
        'descrizione_provincia' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'descrizione' => null,
        'cap' => null,
        'codice_comune' => null,
        'descrizione_comune' => null,
        'codice_comune_istat' => null,
        'provincia' => null,
        'descrizione_provincia' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'descrizione' => 'descrizione',
        'cap' => 'cap',
        'codice_comune' => 'codice_comune',
        'descrizione_comune' => 'descrizione_comune',
        'codice_comune_istat' => 'codice_comune_istat',
        'provincia' => 'provincia',
        'descrizione_provincia' => 'descrizione_provincia'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'descrizione' => 'setDescrizione',
        'cap' => 'setCap',
        'codice_comune' => 'setCodiceComune',
        'descrizione_comune' => 'setDescrizioneComune',
        'codice_comune_istat' => 'setCodiceComuneIstat',
        'provincia' => 'setProvincia',
        'descrizione_provincia' => 'setDescrizioneProvincia'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'descrizione' => 'getDescrizione',
        'cap' => 'getCap',
        'codice_comune' => 'getCodiceComune',
        'descrizione_comune' => 'getDescrizioneComune',
        'codice_comune_istat' => 'getCodiceComuneIstat',
        'provincia' => 'getProvincia',
        'descrizione_provincia' => 'getDescrizioneProvincia'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['descrizione'] = isset($data['descrizione']) ? $data['descrizione'] : null;
        $this->container['cap'] = isset($data['cap']) ? $data['cap'] : null;
        $this->container['codice_comune'] = isset($data['codice_comune']) ? $data['codice_comune'] : null;
        $this->container['descrizione_comune'] = isset($data['descrizione_comune']) ? $data['descrizione_comune'] : null;
        $this->container['codice_comune_istat'] = isset($data['codice_comune_istat']) ? $data['codice_comune_istat'] : null;
        $this->container['provincia'] = isset($data['provincia']) ? $data['provincia'] : null;
        $this->container['descrizione_provincia'] = isset($data['descrizione_provincia']) ? $data['descrizione_provincia'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['descrizione'] === null) {
            $invalidProperties[] = "'descrizione' can't be null";
        }
        if ($this->container['cap'] === null) {
            $invalidProperties[] = "'cap' can't be null";
        }
        if ($this->container['codice_comune'] === null) {
            $invalidProperties[] = "'codice_comune' can't be null";
        }
        if ($this->container['descrizione_comune'] === null) {
            $invalidProperties[] = "'descrizione_comune' can't be null";
        }
        if ($this->container['codice_comune_istat'] === null) {
            $invalidProperties[] = "'codice_comune_istat' can't be null";
        }
        if ($this->container['provincia'] === null) {
            $invalidProperties[] = "'provincia' can't be null";
        }
        if ($this->container['descrizione_provincia'] === null) {
            $invalidProperties[] = "'descrizione_provincia' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets descrizione
     *
     * @return string
     */
    public function getDescrizione()
    {
        return $this->container['descrizione'];
    }

    /**
     * Sets descrizione
     *
     * @param string $descrizione Indirizzo esteso della sede principale del Soggetto
     *
     * @return $this
     */
    public function setDescrizione($descrizione)
    {
        $this->container['descrizione'] = $descrizione;

        return $this;
    }

    /**
     * Gets cap
     *
     * @return string
     */
    public function getCap()
    {
        return $this->container['cap'];
    }

    /**
     * Sets cap
     *
     * @param string $cap Codice di avviamento postale della sede principale del Soggetto
     *
     * @return $this
     */
    public function setCap($cap)
    {
        $this->container['cap'] = $cap;

        return $this;
    }

    /**
     * Gets codice_comune
     *
     * @return string
     */
    public function getCodiceComune()
    {
        return $this->container['codice_comune'];
    }

    /**
     * Sets codice_comune
     *
     * @param string $codice_comune Codice comune Cerved della sede principale del Soggetto
     *
     * @return $this
     */
    public function setCodiceComune($codice_comune)
    {
        $this->container['codice_comune'] = $codice_comune;

        return $this;
    }

    /**
     * Gets descrizione_comune
     *
     * @return string
     */
    public function getDescrizioneComune()
    {
        return $this->container['descrizione_comune'];
    }

    /**
     * Sets descrizione_comune
     *
     * @param string $descrizione_comune Nome esteso del comune della sede principale del Soggetto
     *
     * @return $this
     */
    public function setDescrizioneComune($descrizione_comune)
    {
        $this->container['descrizione_comune'] = $descrizione_comune;

        return $this;
    }

    /**
     * Gets codice_comune_istat
     *
     * @return string
     */
    public function getCodiceComuneIstat()
    {
        return $this->container['codice_comune_istat'];
    }

    /**
     * Sets codice_comune_istat
     *
     * @param string $codice_comune_istat Codice comune ISTAT della sede principale del Soggetto
     *
     * @return $this
     */
    public function setCodiceComuneIstat($codice_comune_istat)
    {
        $this->container['codice_comune_istat'] = $codice_comune_istat;

        return $this;
    }

    /**
     * Gets provincia
     *
     * @return string
     */
    public function getProvincia()
    {
        return $this->container['provincia'];
    }

    /**
     * Sets provincia
     *
     * @param string $provincia Provincia della sede principale del Soggetto
     *
     * @return $this
     */
    public function setProvincia($provincia)
    {
        $this->container['provincia'] = $provincia;

        return $this;
    }

    /**
     * Gets descrizione_provincia
     *
     * @return string
     */
    public function getDescrizioneProvincia()
    {
        return $this->container['descrizione_provincia'];
    }

    /**
     * Sets descrizione_provincia
     *
     * @param string $descrizione_provincia Nome esteso della provincia della sede principale del Soggetto
     *
     * @return $this
     */
    public function setDescrizioneProvincia($descrizione_provincia)
    {
        $this->container['descrizione_provincia'] = $descrizione_provincia;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


