<?php
/**
 * DatiPA
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DatiPA Class Doc Comment
 *
 * @category Class
 * @description Info relative all&#39;appartenenza alla Pubblica Amministrazione o meno
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DatiPA implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DatiPA';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ente' => 'bool',
        'fornitore' => 'bool',
        'partecipata' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ente' => null,
        'fornitore' => null,
        'partecipata' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ente' => 'ente',
        'fornitore' => 'fornitore',
        'partecipata' => 'partecipata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ente' => 'setEnte',
        'fornitore' => 'setFornitore',
        'partecipata' => 'setPartecipata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ente' => 'getEnte',
        'fornitore' => 'getFornitore',
        'partecipata' => 'getPartecipata'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ente'] = isset($data['ente']) ? $data['ente'] : null;
        $this->container['fornitore'] = isset($data['fornitore']) ? $data['fornitore'] : null;
        $this->container['partecipata'] = isset($data['partecipata']) ? $data['partecipata'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['ente'] === null) {
            $invalidProperties[] = "'ente' can't be null";
        }
        if ($this->container['fornitore'] === null) {
            $invalidProperties[] = "'fornitore' can't be null";
        }
        if ($this->container['partecipata'] === null) {
            $invalidProperties[] = "'partecipata' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ente
     *
     * @return bool
     */
    public function getEnte()
    {
        return $this->container['ente'];
    }

    /**
     * Sets ente
     *
     * @param bool $ente E' un soggetto appartenente alla Pubblica Amministrazione
     *
     * @return $this
     */
    public function setEnte($ente)
    {
        $this->container['ente'] = $ente;

        return $this;
    }

    /**
     * Gets fornitore
     *
     * @return bool
     */
    public function getFornitore()
    {
        return $this->container['fornitore'];
    }

    /**
     * Sets fornitore
     *
     * @param bool $fornitore E' un soggetto fornitore della Pubblica Amministrazione
     *
     * @return $this
     */
    public function setFornitore($fornitore)
    {
        $this->container['fornitore'] = $fornitore;

        return $this;
    }

    /**
     * Gets partecipata
     *
     * @return bool
     */
    public function getPartecipata()
    {
        return $this->container['partecipata'];
    }

    /**
     * Sets partecipata
     *
     * @param bool $partecipata E' un soggetto che ha partecipazioni da parte della Pubblica Amministrazione
     *
     * @return $this
     */
    public function setPartecipata($partecipata)
    {
        $this->container['partecipata'] = $partecipata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


