<?php
/**
 * PublicAdministration
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PublicAdministration Class Doc Comment
 *
 * @category Class
 * @description Info sulla relazione tra soggetto e pubblica amministrazione
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PublicAdministration implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PublicAdministration';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'pa_subject' => 'bool',
        'pa_supplier' => 'bool',
        'pa_owned' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'pa_subject' => null,
        'pa_supplier' => null,
        'pa_owned' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'pa_subject' => 'pa_subject',
        'pa_supplier' => 'pa_supplier',
        'pa_owned' => 'pa_owned'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'pa_subject' => 'setPaSubject',
        'pa_supplier' => 'setPaSupplier',
        'pa_owned' => 'setPaOwned'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'pa_subject' => 'getPaSubject',
        'pa_supplier' => 'getPaSupplier',
        'pa_owned' => 'getPaOwned'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['pa_subject'] = isset($data['pa_subject']) ? $data['pa_subject'] : null;
        $this->container['pa_supplier'] = isset($data['pa_supplier']) ? $data['pa_supplier'] : null;
        $this->container['pa_owned'] = isset($data['pa_owned']) ? $data['pa_owned'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets pa_subject
     *
     * @return bool
     */
    public function getPaSubject()
    {
        return $this->container['pa_subject'];
    }

    /**
     * Sets pa_subject
     *
     * @param bool $pa_subject Valore booleano indicante se il soggetto trovato appartiene alla pubblica amministrazione o no
     *
     * @return $this
     */
    public function setPaSubject($pa_subject)
    {
        $this->container['pa_subject'] = $pa_subject;

        return $this;
    }

    /**
     * Gets pa_supplier
     *
     * @return bool
     */
    public function getPaSupplier()
    {
        return $this->container['pa_supplier'];
    }

    /**
     * Sets pa_supplier
     *
     * @param bool $pa_supplier Valore booleano indicante se il soggetto trovato è un fornitore della pubblica amministrazione o no
     *
     * @return $this
     */
    public function setPaSupplier($pa_supplier)
    {
        $this->container['pa_supplier'] = $pa_supplier;

        return $this;
    }

    /**
     * Gets pa_owned
     *
     * @return bool
     */
    public function getPaOwned()
    {
        return $this->container['pa_owned'];
    }

    /**
     * Sets pa_owned
     *
     * @param bool $pa_owned Valore booleano indicante se il soggetto trovato è una società partecipata da un ente pubblico o meno
     *
     * @return $this
     */
    public function setPaOwned($pa_owned)
    {
        $this->container['pa_owned'] = $pa_owned;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


