<?php
/**
 * CompanyInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CompanyInfoTest Class Doc Comment
 *
 * @category    Class
 * @description Info della società trovata
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CompanyInfo"
     */
    public function testCompanyInfo()
    {
    }

    /**
     * Test attribute "legal_form"
     */
    public function testPropertyLegalForm()
    {
    }

    /**
     * Test attribute "activity_status"
     */
    public function testPropertyActivityStatus()
    {
    }

    /**
     * Test attribute "business_name"
     */
    public function testPropertyBusinessName()
    {
    }

    /**
     * Test attribute "economic_activity"
     */
    public function testPropertyEconomicActivity()
    {
    }

    /**
     * Test attribute "head_office"
     */
    public function testPropertyHeadOffice()
    {
    }

    /**
     * Test attribute "lei_code"
     */
    public function testPropertyLeiCode()
    {
    }

    /**
     * Test attribute "operational_flag"
     */
    public function testPropertyOperationalFlag()
    {
    }

    /**
     * Test attribute "public_administration"
     */
    public function testPropertyPublicAdministration()
    {
    }

    /**
     * Test attribute "rea_code"
     */
    public function testPropertyReaCode()
    {
    }

    /**
     * Test attribute "vat_number"
     */
    public function testPropertyVatNumber()
    {
    }

    /**
     * Test attribute "no_rea_data"
     */
    public function testPropertyNoReaData()
    {
    }
}
