<?php
/**
 * DatiAnagraficiCompanyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DatiAnagraficiCompanyTest Class Doc Comment
 *
 * @category    Class
 * @description Dati anagrafici del Soggetto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DatiAnagraficiCompanyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DatiAnagraficiCompany"
     */
    public function testDatiAnagraficiCompany()
    {
    }

    /**
     * Test attribute "id_soggetto"
     */
    public function testPropertyIdSoggetto()
    {
    }

    /**
     * Test attribute "denominazione"
     */
    public function testPropertyDenominazione()
    {
    }

    /**
     * Test attribute "codice_fiscale"
     */
    public function testPropertyCodiceFiscale()
    {
    }

    /**
     * Test attribute "partita_iva"
     */
    public function testPropertyPartitaIva()
    {
    }

    /**
     * Test attribute "indirizzo"
     */
    public function testPropertyIndirizzo()
    {
    }
}
