<?php
/**
 * ReaInputTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReaInputTest Class Doc Comment
 *
 * @category    Class
 * @description Codice Rea del soggetto da ricercare - il tipo di soggetto deve essere company o individual company; quando \&quot;rea\&quot; è usato come parametro di ricerca, \&quot;cciaa\&quot; e \&quot;nrea\&quot; sono valori obbligatori.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReaInputTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReaInput"
     */
    public function testReaInput()
    {
    }

    /**
     * Test attribute "cciaa"
     */
    public function testPropertyCciaa()
    {
    }

    /**
     * Test attribute "rea_number"
     */
    public function testPropertyReaNumber()
    {
    }
}
